// EXPR022 - 1 a 3

const alunos = [
    {
        nome: 'João',
        idade: 20,
        curso: 'Engenharia'
    },
    {
        nome: 'Maria',
        idade: 22,
        curso: 'Medicina'
    },
    {
        nome: 'Pedro',
        idade: 21,
        curso: 'Direito'
    },
    {   
        nome: 'Ana',
        idade: 23,
        curso: 'Engenharia'
    },
    {
        nome: 'Lucas',
        idade: 24,
        curso: 'Computação'
    },
    {
        nome: 'Carla',
        idade: 19,
        curso: 'Psicologia'
    },
    {
        nome: 'Rafael',
        idade: 25,
        curso: 'Administração'
    },
    {
        nome: 'Fernanda',
        idade: 22,
        curso: 'Psicologia'
    },
    {
        nome: 'Gustavo',
        idade: 20,
        curso: 'Psicologia'
    },
    {
        nome: 'Juliana',
        idade: 21,
        curso: 'Química'
    },
    {
        nome: 'Bruno',
        idade: 23,
        curso: 'Matemática'
    },
    {
        nome: 'Camila',
        idade: 24,
        curso: 'Enfermagem'
    },
    {
        nome: 'Thiago',
        idade: 22,
        curso: 'Matemática'
    },
    {
        nome: 'Larissa',
        idade: 20,
        curso: 'História'
    }
];

const jogadores = [
    {
        "id": "15",
        "nome": "TIAGO",
        "pontos": 409,
        "cotas": 33,
        "jogos": 132,
        "vitorias": 60,
        "empates": 33,
        "derrotas": 39,
        "gols_pro": 210,
        "gols_contra": 164,
        "saldo": 46,
        "primeiro": 10,
        "segundo": 11,
        "terceiro": 6,
        "quarto": 6,
        "gols": 34,
        "ass": 25,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "17",
        "nome": "ANDERSON ARAUJO",
        "pontos": 355,
        "cotas": 36,
        "jogos": 144,
        "vitorias": 52,
        "empates": 21,
        "derrotas": 71,
        "gols_pro": 202,
        "gols_contra": 231,
        "saldo": -29,
        "primeiro": 7,
        "segundo": 8,
        "terceiro": 12,
        "quarto": 9,
        "gols": 35,
        "ass": 39,
        "amarelo": 1,
        "vermelho": 1
    },
    {
        "id": "12",
        "nome": "DAVID",
        "pontos": 339,
        "cotas": 31,
        "jogos": 124,
        "vitorias": 49,
        "empates": 24,
        "derrotas": 51,
        "gols_pro": 179,
        "gols_contra": 187,
        "saldo": -8,
        "primeiro": 10,
        "segundo": 3,
        "terceiro": 10,
        "quarto": 8,
        "gols": 27,
        "ass": 29,
        "amarelo": 5,
        "vermelho": 0
    },
    {
        "id": "42",
        "nome": "GABRIEL MIRANDA",
        "pontos": 330,
        "cotas": 30,
        "jogos": 120,
        "vitorias": 51,
        "empates": 20,
        "derrotas": 49,
        "gols_pro": 199,
        "gols_contra": 187,
        "saldo": 12,
        "primeiro": 7,
        "segundo": 7,
        "terceiro": 9,
        "quarto": 7,
        "gols": 69,
        "ass": 25,
        "amarelo": 2,
        "vermelho": 0
    },
    {
        "id": "192",
        "nome": "ENISON",
        "pontos": 303,
        "cotas": 27,
        "jogos": 108,
        "vitorias": 46,
        "empates": 23,
        "derrotas": 39,
        "gols_pro": 176,
        "gols_contra": 164,
        "saldo": 12,
        "primeiro": 7,
        "segundo": 7,
        "terceiro": 6,
        "quarto": 7,
        "gols": 18,
        "ass": 20,
        "amarelo": 2,
        "vermelho": 0
    },
    {
        "id": "13",
        "nome": "RENNAN",
        "pontos": 270,
        "cotas": 28,
        "jogos": 112,
        "vitorias": 37,
        "empates": 27,
        "derrotas": 48,
        "gols_pro": 161,
        "gols_contra": 181,
        "saldo": -20,
        "primeiro": 8,
        "segundo": 2,
        "terceiro": 8,
        "quarto": 10,
        "gols": 41,
        "ass": 17,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "233",
        "nome": "CESAR",
        "pontos": 262,
        "cotas": 26,
        "jogos": 104,
        "vitorias": 36,
        "empates": 25,
        "derrotas": 43,
        "gols_pro": 142,
        "gols_contra": 159,
        "saldo": -17,
        "primeiro": 6,
        "segundo": 4,
        "terceiro": 9,
        "quarto": 7,
        "gols": 3,
        "ass": 0,
        "amarelo": 3,
        "vermelho": 0
    },
    {
        "id": "241",
        "nome": "HÉLIO MATEUS",
        "pontos": 261,
        "cotas": 22,
        "jogos": 88,
        "vitorias": 34,
        "empates": 18,
        "derrotas": 36,
        "gols_pro": 135,
        "gols_contra": 135,
        "saldo": 0,
        "primeiro": 8,
        "segundo": 6,
        "terceiro": 5,
        "quarto": 3,
        "gols": 11,
        "ass": 11,
        "amarelo": 2,
        "vermelho": 0
    },
    {
        "id": "14",
        "nome": "NEGUIM",
        "pontos": 259,
        "cotas": 24,
        "jogos": 96,
        "vitorias": 42,
        "empates": 15,
        "derrotas": 39,
        "gols_pro": 152,
        "gols_contra": 160,
        "saldo": -8,
        "primeiro": 5,
        "segundo": 8,
        "terceiro": 4,
        "quarto": 7,
        "gols": 38,
        "ass": 20,
        "amarelo": 3,
        "vermelho": 1
    },
    {
        "id": "195",
        "nome": "FELIPE RIBEIRO",
        "pontos": 254,
        "cotas": 16,
        "jogos": 64,
        "vitorias": 40,
        "empates": 9,
        "derrotas": 15,
        "gols_pro": 124,
        "gols_contra": 63,
        "saldo": 61,
        "primeiro": 8,
        "segundo": 5,
        "terceiro": 3,
        "quarto": 0,
        "gols": 28,
        "ass": 18,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "29",
        "nome": "LEANDRO LIMA",
        "pontos": 249,
        "cotas": 18,
        "jogos": 72,
        "vitorias": 36,
        "empates": 18,
        "derrotas": 18,
        "gols_pro": 131,
        "gols_contra": 80,
        "saldo": 51,
        "primeiro": 8,
        "segundo": 3,
        "terceiro": 5,
        "quarto": 2,
        "gols": 8,
        "ass": 3,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "9",
        "nome": "SIMAO",
        "pontos": 243,
        "cotas": 25,
        "jogos": 100,
        "vitorias": 40,
        "empates": 17,
        "derrotas": 43,
        "gols_pro": 149,
        "gols_contra": 149,
        "saldo": 0,
        "primeiro": 5,
        "segundo": 6,
        "terceiro": 4,
        "quarto": 10,
        "gols": 18,
        "ass": 13,
        "amarelo": 2,
        "vermelho": 0
    },
    {
        "id": "55",
        "nome": "ITALO GABRIEL",
        "pontos": 237,
        "cotas": 19,
        "jogos": 76,
        "vitorias": 35,
        "empates": 15,
        "derrotas": 26,
        "gols_pro": 128,
        "gols_contra": 111,
        "saldo": 17,
        "primeiro": 4,
        "segundo": 7,
        "terceiro": 7,
        "quarto": 1,
        "gols": 19,
        "ass": 19,
        "amarelo": 2,
        "vermelho": 0
    },
    {
        "id": "40",
        "nome": "LEIRTON",
        "pontos": 228,
        "cotas": 16,
        "jogos": 64,
        "vitorias": 35,
        "empates": 12,
        "derrotas": 17,
        "gols_pro": 112,
        "gols_contra": 86,
        "saldo": 26,
        "primeiro": 6,
        "segundo": 6,
        "terceiro": 3,
        "quarto": 1,
        "gols": 27,
        "ass": 16,
        "amarelo": 2,
        "vermelho": 0
    },
    {
        "id": "26",
        "nome": "FARAY",
        "pontos": 199,
        "cotas": 21,
        "jogos": 84,
        "vitorias": 28,
        "empates": 20,
        "derrotas": 36,
        "gols_pro": 104,
        "gols_contra": 129,
        "saldo": -25,
        "primeiro": 6,
        "segundo": 5,
        "terceiro": 1,
        "quarto": 9,
        "gols": 2,
        "ass": 4,
        "amarelo": 1,
        "vermelho": 1
    },
    {
        "id": "11",
        "nome": "EUDES",
        "pontos": 195,
        "cotas": 18,
        "jogos": 72,
        "vitorias": 31,
        "empates": 13,
        "derrotas": 28,
        "gols_pro": 117,
        "gols_contra": 108,
        "saldo": 9,
        "primeiro": 4,
        "segundo": 4,
        "terceiro": 5,
        "quarto": 5,
        "gols": 11,
        "ass": 3,
        "amarelo": 5,
        "vermelho": 0
    },
    {
        "id": "46",
        "nome": "ALAN FERREIRA",
        "pontos": 189,
        "cotas": 17,
        "jogos": 68,
        "vitorias": 26,
        "empates": 10,
        "derrotas": 32,
        "gols_pro": 93,
        "gols_contra": 117,
        "saldo": -24,
        "primeiro": 7,
        "segundo": 1,
        "terceiro": 5,
        "quarto": 4,
        "gols": 11,
        "ass": 10,
        "amarelo": 6,
        "vermelho": 0
    },
    {
        "id": "236",
        "nome": "ALEX",
        "pontos": 185,
        "cotas": 23,
        "jogos": 92,
        "vitorias": 26,
        "empates": 27,
        "derrotas": 39,
        "gols_pro": 107,
        "gols_contra": 159,
        "saldo": -52,
        "primeiro": 2,
        "segundo": 10,
        "terceiro": 0,
        "quarto": 11,
        "gols": 2,
        "ass": 4,
        "amarelo": 4,
        "vermelho": 0
    },
    {
        "id": "188",
        "nome": "MOISES",
        "pontos": 182,
        "cotas": 19,
        "jogos": 76,
        "vitorias": 26,
        "empates": 17,
        "derrotas": 33,
        "gols_pro": 106,
        "gols_contra": 120,
        "saldo": -14,
        "primeiro": 7,
        "segundo": 2,
        "terceiro": 1,
        "quarto": 9,
        "gols": 34,
        "ass": 24,
        "amarelo": 2,
        "vermelho": 0
    },
    {
        "id": "186",
        "nome": "IGOR HENRIQUE",
        "pontos": 180,
        "cotas": 15,
        "jogos": 60,
        "vitorias": 23,
        "empates": 17,
        "derrotas": 20,
        "gols_pro": 77,
        "gols_contra": 81,
        "saldo": -4,
        "primeiro": 5,
        "segundo": 4,
        "terceiro": 4,
        "quarto": 2,
        "gols": 25,
        "ass": 6,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "234",
        "nome": "GABRIEL (ALEX)",
        "pontos": 176,
        "cotas": 16,
        "jogos": 64,
        "vitorias": 25,
        "empates": 14,
        "derrotas": 25,
        "gols_pro": 105,
        "gols_contra": 94,
        "saldo": 11,
        "primeiro": 4,
        "segundo": 2,
        "terceiro": 7,
        "quarto": 3,
        "gols": 36,
        "ass": 9,
        "amarelo": 4,
        "vermelho": 0
    },
    {
        "id": "211",
        "nome": "VICTOR FERRAZ",
        "pontos": 160,
        "cotas": 13,
        "jogos": 52,
        "vitorias": 25,
        "empates": 11,
        "derrotas": 16,
        "gols_pro": 87,
        "gols_contra": 64,
        "saldo": 23,
        "primeiro": 4,
        "segundo": 4,
        "terceiro": 2,
        "quarto": 3,
        "gols": 24,
        "ass": 11,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "7",
        "nome": "BABU",
        "pontos": 159,
        "cotas": 13,
        "jogos": 52,
        "vitorias": 24,
        "empates": 12,
        "derrotas": 16,
        "gols_pro": 90,
        "gols_contra": 60,
        "saldo": 30,
        "primeiro": 3,
        "segundo": 5,
        "terceiro": 3,
        "quarto": 2,
        "gols": 10,
        "ass": 8,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "49",
        "nome": "DIEGO",
        "pontos": 154,
        "cotas": 13,
        "jogos": 52,
        "vitorias": 24,
        "empates": 10,
        "derrotas": 18,
        "gols_pro": 95,
        "gols_contra": 79,
        "saldo": 16,
        "primeiro": 3,
        "segundo": 2,
        "terceiro": 6,
        "quarto": 2,
        "gols": 31,
        "ass": 21,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "183",
        "nome": "RAFAEL LIMA",
        "pontos": 143,
        "cotas": 10,
        "jogos": 40,
        "vitorias": 22,
        "empates": 8,
        "derrotas": 10,
        "gols_pro": 58,
        "gols_contra": 42,
        "saldo": 16,
        "primeiro": 4,
        "segundo": 4,
        "terceiro": 1,
        "quarto": 1,
        "gols": 5,
        "ass": 9,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "189",
        "nome": "DENNYS",
        "pontos": 141,
        "cotas": 10,
        "jogos": 40,
        "vitorias": 22,
        "empates": 7,
        "derrotas": 11,
        "gols_pro": 69,
        "gols_contra": 54,
        "saldo": 15,
        "primeiro": 4,
        "segundo": 3,
        "terceiro": 2,
        "quarto": 1,
        "gols": 5,
        "ass": 1,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "8",
        "nome": "LUCAS LIMA",
        "pontos": 135,
        "cotas": 15,
        "jogos": 60,
        "vitorias": 20,
        "empates": 7,
        "derrotas": 33,
        "gols_pro": 99,
        "gols_contra": 122,
        "saldo": -23,
        "primeiro": 3,
        "segundo": 3,
        "terceiro": 4,
        "quarto": 5,
        "gols": 19,
        "ass": 14,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "266",
        "nome": "FABIO COLOMBIA",
        "pontos": 126,
        "cotas": 12,
        "jogos": 48,
        "vitorias": 18,
        "empates": 10,
        "derrotas": 20,
        "gols_pro": 61,
        "gols_contra": 78,
        "saldo": -17,
        "primeiro": 4,
        "segundo": 2,
        "terceiro": 2,
        "quarto": 4,
        "gols": 13,
        "ass": 9,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "38",
        "nome": "GUSTAVO SILVA",
        "pontos": 125,
        "cotas": 11,
        "jogos": 44,
        "vitorias": 17,
        "empates": 8,
        "derrotas": 19,
        "gols_pro": 54,
        "gols_contra": 52,
        "saldo": 2,
        "primeiro": 4,
        "segundo": 1,
        "terceiro": 4,
        "quarto": 2,
        "gols": 4,
        "ass": 1,
        "amarelo": 2,
        "vermelho": 0
    },
    {
        "id": "244",
        "nome": "MARQUIM (BAXOTE)",
        "pontos": 125,
        "cotas": 12,
        "jogos": 48,
        "vitorias": 17,
        "empates": 14,
        "derrotas": 17,
        "gols_pro": 54,
        "gols_contra": 57,
        "saldo": -3,
        "primeiro": 2,
        "segundo": 5,
        "terceiro": 2,
        "quarto": 3,
        "gols": 10,
        "ass": 7,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "202",
        "nome": "MIRO",
        "pontos": 119,
        "cotas": 10,
        "jogos": 40,
        "vitorias": 18,
        "empates": 6,
        "derrotas": 16,
        "gols_pro": 71,
        "gols_contra": 54,
        "saldo": 17,
        "primeiro": 1,
        "segundo": 4,
        "terceiro": 5,
        "quarto": 0,
        "gols": 1,
        "ass": 1,
        "amarelo": 3,
        "vermelho": 0
    },
    {
        "id": "191",
        "nome": "ITALO MESQUITA",
        "pontos": 116,
        "cotas": 12,
        "jogos": 48,
        "vitorias": 21,
        "empates": 5,
        "derrotas": 22,
        "gols_pro": 79,
        "gols_contra": 71,
        "saldo": 8,
        "primeiro": 2,
        "segundo": 3,
        "terceiro": 2,
        "quarto": 5,
        "gols": 13,
        "ass": 10,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "201",
        "nome": "VICTOR FRANCO",
        "pontos": 115,
        "cotas": 10,
        "jogos": 40,
        "vitorias": 16,
        "empates": 9,
        "derrotas": 15,
        "gols_pro": 57,
        "gols_contra": 49,
        "saldo": 8,
        "primeiro": 2,
        "segundo": 3,
        "terceiro": 4,
        "quarto": 1,
        "gols": 4,
        "ass": 5,
        "amarelo": 2,
        "vermelho": 0
    },
    {
        "id": "208",
        "nome": "BAXOTE",
        "pontos": 109,
        "cotas": 13,
        "jogos": 52,
        "vitorias": 14,
        "empates": 13,
        "derrotas": 25,
        "gols_pro": 62,
        "gols_contra": 96,
        "saldo": -34,
        "primeiro": 2,
        "segundo": 4,
        "terceiro": 2,
        "quarto": 5,
        "gols": 3,
        "ass": 4,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "190",
        "nome": "YAGO",
        "pontos": 105,
        "cotas": 8,
        "jogos": 32,
        "vitorias": 17,
        "empates": 7,
        "derrotas": 8,
        "gols_pro": 51,
        "gols_contra": 35,
        "saldo": 16,
        "primeiro": 3,
        "segundo": 2,
        "terceiro": 1,
        "quarto": 2,
        "gols": 6,
        "ass": 8,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "200",
        "nome": "LUCAS FERNANDES",
        "pontos": 94,
        "cotas": 9,
        "jogos": 36,
        "vitorias": 13,
        "empates": 8,
        "derrotas": 15,
        "gols_pro": 50,
        "gols_contra": 46,
        "saldo": 4,
        "primeiro": 1,
        "segundo": 2,
        "terceiro": 5,
        "quarto": 1,
        "gols": 3,
        "ass": 4,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "19",
        "nome": "ROBERTO BARROS",
        "pontos": 90,
        "cotas": 7,
        "jogos": 28,
        "vitorias": 13,
        "empates": 4,
        "derrotas": 11,
        "gols_pro": 38,
        "gols_contra": 36,
        "saldo": 2,
        "primeiro": 3,
        "segundo": 2,
        "terceiro": 1,
        "quarto": 1,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "243",
        "nome": "MEXICANO (BAXOTE)",
        "pontos": 89,
        "cotas": 8,
        "jogos": 32,
        "vitorias": 13,
        "empates": 8,
        "derrotas": 11,
        "gols_pro": 53,
        "gols_contra": 43,
        "saldo": 10,
        "primeiro": 1,
        "segundo": 2,
        "terceiro": 4,
        "quarto": 1,
        "gols": 11,
        "ass": 6,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "205",
        "nome": "WANDERSON",
        "pontos": 83,
        "cotas": 7,
        "jogos": 28,
        "vitorias": 11,
        "empates": 7,
        "derrotas": 10,
        "gols_pro": 47,
        "gols_contra": 37,
        "saldo": 10,
        "primeiro": 2,
        "segundo": 3,
        "terceiro": 1,
        "quarto": 1,
        "gols": 15,
        "ass": 10,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "194",
        "nome": "AFONSO",
        "pontos": 82,
        "cotas": 7,
        "jogos": 28,
        "vitorias": 13,
        "empates": 5,
        "derrotas": 10,
        "gols_pro": 54,
        "gols_contra": 41,
        "saldo": 13,
        "primeiro": 1,
        "segundo": 3,
        "terceiro": 2,
        "quarto": 1,
        "gols": 16,
        "ass": 6,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "10",
        "nome": "MIKAEL",
        "pontos": 79,
        "cotas": 7,
        "jogos": 28,
        "vitorias": 13,
        "empates": 4,
        "derrotas": 11,
        "gols_pro": 38,
        "gols_contra": 37,
        "saldo": 1,
        "primeiro": 2,
        "segundo": 1,
        "terceiro": 2,
        "quarto": 2,
        "gols": 7,
        "ass": 8,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "262",
        "nome": "GABRIEL (LEONES)",
        "pontos": 79,
        "cotas": 10,
        "jogos": 40,
        "vitorias": 11,
        "empates": 9,
        "derrotas": 20,
        "gols_pro": 46,
        "gols_contra": 65,
        "saldo": -19,
        "primeiro": 1,
        "segundo": 2,
        "terceiro": 3,
        "quarto": 4,
        "gols": 9,
        "ass": 3,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "209",
        "nome": "FIRMINO",
        "pontos": 78,
        "cotas": 5,
        "jogos": 20,
        "vitorias": 11,
        "empates": 3,
        "derrotas": 6,
        "gols_pro": 38,
        "gols_contra": 27,
        "saldo": 11,
        "primeiro": 3,
        "segundo": 2,
        "terceiro": 0,
        "quarto": 0,
        "gols": 8,
        "ass": 3,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "22",
        "nome": "LUCAS TELES",
        "pontos": 77,
        "cotas": 5,
        "jogos": 20,
        "vitorias": 11,
        "empates": 4,
        "derrotas": 5,
        "gols_pro": 31,
        "gols_contra": 23,
        "saldo": 8,
        "primeiro": 4,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 12,
        "ass": 6,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "56",
        "nome": "ALAN FARIAS",
        "pontos": 69,
        "cotas": 7,
        "jogos": 28,
        "vitorias": 12,
        "empates": 4,
        "derrotas": 12,
        "gols_pro": 43,
        "gols_contra": 48,
        "saldo": -5,
        "primeiro": 0,
        "segundo": 4,
        "terceiro": 1,
        "quarto": 2,
        "gols": 11,
        "ass": 9,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "128",
        "nome": "NESTOR",
        "pontos": 69,
        "cotas": 8,
        "jogos": 32,
        "vitorias": 10,
        "empates": 6,
        "derrotas": 16,
        "gols_pro": 48,
        "gols_contra": 63,
        "saldo": -15,
        "primeiro": 1,
        "segundo": 3,
        "terceiro": 1,
        "quarto": 3,
        "gols": 7,
        "ass": 8,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "279",
        "nome": "NICK BALA",
        "pontos": 67,
        "cotas": 5,
        "jogos": 20,
        "vitorias": 9,
        "empates": 5,
        "derrotas": 6,
        "gols_pro": 34,
        "gols_contra": 26,
        "saldo": 8,
        "primeiro": 2,
        "segundo": 0,
        "terceiro": 3,
        "quarto": 0,
        "gols": 10,
        "ass": 5,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "228",
        "nome": "SANCHES",
        "pontos": 66,
        "cotas": 6,
        "jogos": 24,
        "vitorias": 11,
        "empates": 5,
        "derrotas": 8,
        "gols_pro": 30,
        "gols_contra": 35,
        "saldo": -5,
        "primeiro": 1,
        "segundo": 3,
        "terceiro": 0,
        "quarto": 2,
        "gols": 0,
        "ass": 0,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "18",
        "nome": "JUNIOR",
        "pontos": 66,
        "cotas": 6,
        "jogos": 24,
        "vitorias": 12,
        "empates": 3,
        "derrotas": 9,
        "gols_pro": 32,
        "gols_contra": 31,
        "saldo": 1,
        "primeiro": 1,
        "segundo": 2,
        "terceiro": 1,
        "quarto": 2,
        "gols": 10,
        "ass": 8,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "66",
        "nome": "FELIPE ARAUJO",
        "pontos": 64,
        "cotas": 6,
        "jogos": 24,
        "vitorias": 10,
        "empates": 2,
        "derrotas": 12,
        "gols_pro": 41,
        "gols_contra": 50,
        "saldo": -9,
        "primeiro": 0,
        "segundo": 2,
        "terceiro": 4,
        "quarto": 0,
        "gols": 9,
        "ass": 9,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "198",
        "nome": "EDSON",
        "pontos": 60,
        "cotas": 4,
        "jogos": 16,
        "vitorias": 7,
        "empates": 4,
        "derrotas": 5,
        "gols_pro": 24,
        "gols_contra": 26,
        "saldo": -2,
        "primeiro": 3,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 0,
        "gols": 4,
        "ass": 4,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "265",
        "nome": "FERNANDO (FARAY)",
        "pontos": 60,
        "cotas": 6,
        "jogos": 24,
        "vitorias": 7,
        "empates": 8,
        "derrotas": 9,
        "gols_pro": 29,
        "gols_contra": 30,
        "saldo": -1,
        "primeiro": 2,
        "segundo": 1,
        "terceiro": 1,
        "quarto": 2,
        "gols": 4,
        "ass": 4,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "184",
        "nome": "JEAN MATHEUS",
        "pontos": 58,
        "cotas": 5,
        "jogos": 20,
        "vitorias": 9,
        "empates": 4,
        "derrotas": 7,
        "gols_pro": 25,
        "gols_contra": 27,
        "saldo": -2,
        "primeiro": 1,
        "segundo": 2,
        "terceiro": 1,
        "quarto": 1,
        "gols": 4,
        "ass": 2,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "221",
        "nome": "THIAGO LOPES",
        "pontos": 55,
        "cotas": 4,
        "jogos": 16,
        "vitorias": 9,
        "empates": 2,
        "derrotas": 5,
        "gols_pro": 29,
        "gols_contra": 14,
        "saldo": 15,
        "primeiro": 1,
        "segundo": 1,
        "terceiro": 2,
        "quarto": 0,
        "gols": 10,
        "ass": 5,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "278",
        "nome": "LIDENBERG",
        "pontos": 50,
        "cotas": 6,
        "jogos": 24,
        "vitorias": 5,
        "empates": 9,
        "derrotas": 10,
        "gols_pro": 33,
        "gols_contra": 44,
        "saldo": -11,
        "primeiro": 1,
        "segundo": 1,
        "terceiro": 2,
        "quarto": 2,
        "gols": 8,
        "ass": 1,
        "amarelo": 3,
        "vermelho": 0
    },
    {
        "id": "231",
        "nome": "WELTON",
        "pontos": 46,
        "cotas": 3,
        "jogos": 12,
        "vitorias": 7,
        "empates": 3,
        "derrotas": 2,
        "gols_pro": 20,
        "gols_contra": 12,
        "saldo": 8,
        "primeiro": 1,
        "segundo": 2,
        "terceiro": 0,
        "quarto": 0,
        "gols": 3,
        "ass": 2,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "282",
        "nome": "IVO (GABRIEL MIRANDA)",
        "pontos": 43,
        "cotas": 3,
        "jogos": 12,
        "vitorias": 7,
        "empates": 1,
        "derrotas": 4,
        "gols_pro": 20,
        "gols_contra": 16,
        "saldo": 4,
        "primeiro": 1,
        "segundo": 1,
        "terceiro": 1,
        "quarto": 0,
        "gols": 5,
        "ass": 2,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "224",
        "nome": "BRUNO (GABRIEL MIRANDA)",
        "pontos": 42,
        "cotas": 4,
        "jogos": 16,
        "vitorias": 6,
        "empates": 3,
        "derrotas": 7,
        "gols_pro": 20,
        "gols_contra": 18,
        "saldo": 2,
        "primeiro": 1,
        "segundo": 1,
        "terceiro": 1,
        "quarto": 1,
        "gols": 0,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "267",
        "nome": "GABRIEL COSTA (ALEX)",
        "pontos": 41,
        "cotas": 3,
        "jogos": 12,
        "vitorias": 6,
        "empates": 2,
        "derrotas": 4,
        "gols_pro": 19,
        "gols_contra": 17,
        "saldo": 2,
        "primeiro": 1,
        "segundo": 1,
        "terceiro": 1,
        "quarto": 0,
        "gols": 6,
        "ass": 4,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "245",
        "nome": "ICARO (ENISON)",
        "pontos": 36,
        "cotas": 3,
        "jogos": 12,
        "vitorias": 6,
        "empates": 2,
        "derrotas": 4,
        "gols_pro": 13,
        "gols_contra": 8,
        "saldo": 5,
        "primeiro": 1,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 1,
        "gols": 1,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "20",
        "nome": "JEFFERSON SILVA",
        "pontos": 32,
        "cotas": 8,
        "jogos": 32,
        "vitorias": 5,
        "empates": 2,
        "derrotas": 25,
        "gols_pro": 28,
        "gols_contra": 68,
        "saldo": -40,
        "primeiro": 1,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 6,
        "gols": 2,
        "ass": 1,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "217",
        "nome": "LEONES",
        "pontos": 31,
        "cotas": 3,
        "jogos": 12,
        "vitorias": 3,
        "empates": 5,
        "derrotas": 4,
        "gols_pro": 15,
        "gols_contra": 20,
        "saldo": -5,
        "primeiro": 0,
        "segundo": 2,
        "terceiro": 1,
        "quarto": 0,
        "gols": 0,
        "ass": 0,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "103",
        "nome": "RODRIGO",
        "pontos": 31,
        "cotas": 3,
        "jogos": 12,
        "vitorias": 6,
        "empates": 2,
        "derrotas": 4,
        "gols_pro": 20,
        "gols_contra": 14,
        "saldo": 6,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 1,
        "quarto": 1,
        "gols": 6,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "203",
        "nome": "PATRICK",
        "pontos": 30,
        "cotas": 4,
        "jogos": 16,
        "vitorias": 4,
        "empates": 3,
        "derrotas": 9,
        "gols_pro": 25,
        "gols_contra": 36,
        "saldo": -11,
        "primeiro": 1,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 2,
        "gols": 2,
        "ass": 4,
        "amarelo": 2,
        "vermelho": 0
    },
    {
        "id": "242",
        "nome": "THIAGO MACIEL (ANDERSON)",
        "pontos": 29,
        "cotas": 2,
        "jogos": 8,
        "vitorias": 4,
        "empates": 2,
        "derrotas": 2,
        "gols_pro": 12,
        "gols_contra": 7,
        "saldo": 5,
        "primeiro": 1,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 0,
        "gols": 0,
        "ass": 0,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "185",
        "nome": "GUILHERME DE LA ROCHA",
        "pontos": 27,
        "cotas": 3,
        "jogos": 12,
        "vitorias": 4,
        "empates": 0,
        "derrotas": 8,
        "gols_pro": 14,
        "gols_contra": 28,
        "saldo": -14,
        "primeiro": 1,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 1,
        "gols": 2,
        "ass": 2,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "273",
        "nome": "PAULO ERIC",
        "pontos": 26,
        "cotas": 2,
        "jogos": 8,
        "vitorias": 4,
        "empates": 3,
        "derrotas": 1,
        "gols_pro": 10,
        "gols_contra": 7,
        "saldo": 3,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 1,
        "quarto": 0,
        "gols": 3,
        "ass": 1,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "294",
        "nome": "GABRIEL GOMES",
        "pontos": 24,
        "cotas": 2,
        "jogos": 8,
        "vitorias": 3,
        "empates": 4,
        "derrotas": 1,
        "gols_pro": 10,
        "gols_contra": 7,
        "saldo": 3,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 1,
        "quarto": 0,
        "gols": 3,
        "ass": 2,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "293",
        "nome": "MACGYVER",
        "pontos": 23,
        "cotas": 2,
        "jogos": 8,
        "vitorias": 3,
        "empates": 4,
        "derrotas": 1,
        "gols_pro": 17,
        "gols_contra": 14,
        "saldo": 3,
        "primeiro": 1,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 1,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "216",
        "nome": "JOEL (GABRIEL MIRANDA)",
        "pontos": 23,
        "cotas": 3,
        "jogos": 12,
        "vitorias": 3,
        "empates": 2,
        "derrotas": 7,
        "gols_pro": 14,
        "gols_contra": 20,
        "saldo": -6,
        "primeiro": 0,
        "segundo": 2,
        "terceiro": 0,
        "quarto": 1,
        "gols": 2,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "299",
        "nome": "IURY BAHIA",
        "pontos": 23,
        "cotas": 3,
        "jogos": 12,
        "vitorias": 4,
        "empates": 0,
        "derrotas": 8,
        "gols_pro": 17,
        "gols_contra": 30,
        "saldo": -13,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 1,
        "quarto": 1,
        "gols": 0,
        "ass": 2,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "271",
        "nome": "FABIANO",
        "pontos": 22,
        "cotas": 2,
        "jogos": 8,
        "vitorias": 3,
        "empates": 3,
        "derrotas": 2,
        "gols_pro": 8,
        "gols_contra": 6,
        "saldo": 2,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 2,
        "quarto": 0,
        "gols": 1,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "31",
        "nome": "MARCIO",
        "pontos": 20,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 3,
        "empates": 1,
        "derrotas": 0,
        "gols_pro": 7,
        "gols_contra": 2,
        "saldo": 5,
        "primeiro": 1,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 0,
        "gols": 1,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "277",
        "nome": "GRITTI",
        "pontos": 20,
        "cotas": 2,
        "jogos": 8,
        "vitorias": 2,
        "empates": 4,
        "derrotas": 2,
        "gols_pro": 10,
        "gols_contra": 8,
        "saldo": 2,
        "primeiro": 1,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 0,
        "ass": 4,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "249",
        "nome": "JACÓ (DAVID)",
        "pontos": 20,
        "cotas": 2,
        "jogos": 8,
        "vitorias": 3,
        "empates": 1,
        "derrotas": 4,
        "gols_pro": 15,
        "gols_contra": 16,
        "saldo": -1,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 2,
        "quarto": 0,
        "gols": 2,
        "ass": 1,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "275",
        "nome": "RUDSON (FARAY)",
        "pontos": 17,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 1,
        "derrotas": 1,
        "gols_pro": 8,
        "gols_contra": 3,
        "saldo": 5,
        "primeiro": 1,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 0,
        "gols": 0,
        "ass": 2,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "214",
        "nome": "WELLITON",
        "pontos": 17,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 1,
        "derrotas": 1,
        "gols_pro": 10,
        "gols_contra": 6,
        "saldo": 4,
        "primeiro": 1,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 0,
        "gols": 3,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "283",
        "nome": "MATEUS ESCOSSIO (DAVID)",
        "pontos": 17,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 1,
        "derrotas": 1,
        "gols_pro": 6,
        "gols_contra": 4,
        "saldo": 2,
        "primeiro": 1,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 0,
        "gols": 1,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "274",
        "nome": "JONAS (FARAY)",
        "pontos": 17,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 1,
        "derrotas": 1,
        "gols_pro": 8,
        "gols_contra": 3,
        "saldo": 5,
        "primeiro": 1,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 0,
        "gols": 4,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "300",
        "nome": "ANDERSON (VICTOR FERRAZ)",
        "pontos": 17,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 1,
        "derrotas": 1,
        "gols_pro": 8,
        "gols_contra": 4,
        "saldo": 4,
        "primeiro": 1,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 0,
        "gols": 1,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "213",
        "nome": "CARLIM",
        "pontos": 17,
        "cotas": 2,
        "jogos": 8,
        "vitorias": 1,
        "empates": 3,
        "derrotas": 4,
        "gols_pro": 12,
        "gols_contra": 17,
        "saldo": -5,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 1,
        "quarto": 0,
        "gols": 2,
        "ass": 5,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "197",
        "nome": "WILL",
        "pontos": 17,
        "cotas": 3,
        "jogos": 12,
        "vitorias": 3,
        "empates": 2,
        "derrotas": 7,
        "gols_pro": 13,
        "gols_contra": 26,
        "saldo": -13,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 2,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "250",
        "nome": "ITALO (LEVI)",
        "pontos": 16,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 3,
        "derrotas": 0,
        "gols_pro": 4,
        "gols_contra": 2,
        "saldo": 2,
        "primeiro": 1,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 0,
        "gols": 1,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "264",
        "nome": "MAICON (FARAY)",
        "pontos": 16,
        "cotas": 2,
        "jogos": 8,
        "vitorias": 2,
        "empates": 4,
        "derrotas": 2,
        "gols_pro": 11,
        "gols_contra": 12,
        "saldo": -1,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 1,
        "gols": 3,
        "ass": 2,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "212",
        "nome": "FREITAS (ENISON)",
        "pontos": 15,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 3,
        "empates": 0,
        "derrotas": 1,
        "gols_pro": 8,
        "gols_contra": 5,
        "saldo": 3,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 0,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "210",
        "nome": "JEFFERSON COSTA",
        "pontos": 15,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 3,
        "empates": 0,
        "derrotas": 1,
        "gols_pro": 8,
        "gols_contra": 5,
        "saldo": 3,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 0,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "219",
        "nome": "EMANUEL (JUNIOR)",
        "pontos": 14,
        "cotas": 2,
        "jogos": 8,
        "vitorias": 3,
        "empates": 0,
        "derrotas": 5,
        "gols_pro": 11,
        "gols_contra": 20,
        "saldo": -9,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 1,
        "gols": 0,
        "ass": 0,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "223",
        "nome": "WESCLEY (ANTARES)",
        "pontos": 14,
        "cotas": 2,
        "jogos": 8,
        "vitorias": 2,
        "empates": 2,
        "derrotas": 4,
        "gols_pro": 11,
        "gols_contra": 12,
        "saldo": -1,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 1,
        "gols": 1,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "226",
        "nome": "ANTARES",
        "pontos": 14,
        "cotas": 2,
        "jogos": 8,
        "vitorias": 3,
        "empates": 0,
        "derrotas": 5,
        "gols_pro": 10,
        "gols_contra": 15,
        "saldo": -5,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 1,
        "gols": 2,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "287",
        "nome": "RUMARIO (DAVID)",
        "pontos": 13,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 1,
        "derrotas": 1,
        "gols_pro": 5,
        "gols_contra": 4,
        "saldo": 1,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 0,
        "gols": 1,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "292",
        "nome": "FELIPE COLOMBIA (FARAY)",
        "pontos": 13,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 1,
        "derrotas": 1,
        "gols_pro": 5,
        "gols_contra": 4,
        "saldo": 1,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 0,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "295",
        "nome": "VIRTO (GABRIEL MIRANDA)",
        "pontos": 13,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 1,
        "derrotas": 1,
        "gols_pro": 5,
        "gols_contra": 2,
        "saldo": 3,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 0,
        "gols": 1,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "286",
        "nome": "LEO (DAVID)",
        "pontos": 13,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 1,
        "derrotas": 1,
        "gols_pro": 5,
        "gols_contra": 4,
        "saldo": 1,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 0,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "280",
        "nome": "DAVID (COLOMBIANO)",
        "pontos": 12,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 1,
        "derrotas": 1,
        "gols_pro": 10,
        "gols_contra": 4,
        "saldo": 6,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 0,
        "gols": 1,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "248",
        "nome": "ITALO FRANCISCO",
        "pontos": 12,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 0,
        "derrotas": 2,
        "gols_pro": 8,
        "gols_contra": 5,
        "saldo": 3,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 0,
        "gols": 0,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "298",
        "nome": "CARLIM (VICTOR FERRAZ)",
        "pontos": 12,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 3,
        "derrotas": 0,
        "gols_pro": 5,
        "gols_contra": 4,
        "saldo": 1,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 0,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "218",
        "nome": "RONALDO (MOISES)",
        "pontos": 12,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 1,
        "derrotas": 1,
        "gols_pro": 8,
        "gols_contra": 9,
        "saldo": -1,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 0,
        "gols": 2,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "50",
        "nome": "DJALMA",
        "pontos": 12,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 1,
        "derrotas": 1,
        "gols_pro": 7,
        "gols_contra": 2,
        "saldo": 5,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 0,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "222",
        "nome": "FELIPE (ANTARES)",
        "pontos": 12,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 0,
        "derrotas": 2,
        "gols_pro": 7,
        "gols_contra": 5,
        "saldo": 2,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 0,
        "gols": 2,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "220",
        "nome": "ANDERSON RAMOS",
        "pontos": 11,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 2,
        "derrotas": 1,
        "gols_pro": 5,
        "gols_contra": 6,
        "saldo": -1,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 0,
        "gols": 0,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "268",
        "nome": "BRUNO PESSOA",
        "pontos": 11,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 2,
        "derrotas": 1,
        "gols_pro": 5,
        "gols_contra": 6,
        "saldo": -1,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 0,
        "gols": 0,
        "ass": 0,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "225",
        "nome": "JEFFERSON ALVES",
        "pontos": 11,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 0,
        "derrotas": 2,
        "gols_pro": 6,
        "gols_contra": 8,
        "saldo": -2,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 0,
        "gols": 2,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "263",
        "nome": "LEANDRO NOGUEIRA",
        "pontos": 11,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 0,
        "derrotas": 2,
        "gols_pro": 11,
        "gols_contra": 7,
        "saldo": 4,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 0,
        "gols": 2,
        "ass": 2,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "215",
        "nome": "JONATHAN (MOISES)",
        "pontos": 11,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 2,
        "derrotas": 1,
        "gols_pro": 6,
        "gols_contra": 7,
        "saldo": -1,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 0,
        "gols": 0,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "227",
        "nome": "LUCAS ACACIO (GABRIEL MIRANDA)",
        "pontos": 11,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 0,
        "derrotas": 2,
        "gols_pro": 6,
        "gols_contra": 8,
        "saldo": -2,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 0,
        "gols": 0,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "247",
        "nome": "THARLYS (ANTARES)",
        "pontos": 11,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 2,
        "derrotas": 1,
        "gols_pro": 6,
        "gols_contra": 6,
        "saldo": 0,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 0,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "246",
        "nome": "THIAGO NEGUEBA",
        "pontos": 11,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 2,
        "derrotas": 1,
        "gols_pro": 6,
        "gols_contra": 6,
        "saldo": 0,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 0,
        "gols": 5,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "235",
        "nome": "JOEL (ITALO GABRIEL)",
        "pontos": 11,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 2,
        "empates": 0,
        "derrotas": 2,
        "gols_pro": 11,
        "gols_contra": 7,
        "saldo": 4,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 0,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "284",
        "nome": "CLENILSON",
        "pontos": 10,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 2,
        "derrotas": 1,
        "gols_pro": 6,
        "gols_contra": 5,
        "saldo": 1,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 0,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "232",
        "nome": "GLEUCIMAR (MIKAEL)",
        "pontos": 10,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 1,
        "derrotas": 2,
        "gols_pro": 5,
        "gols_contra": 6,
        "saldo": -1,
        "primeiro": 0,
        "segundo": 1,
        "terceiro": 0,
        "quarto": 0,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "285",
        "nome": "MIGUEL (DAVID)",
        "pontos": 10,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 2,
        "derrotas": 1,
        "gols_pro": 6,
        "gols_contra": 5,
        "saldo": 1,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 0,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "253",
        "nome": "JORGE (MOISES)",
        "pontos": 9,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 1,
        "derrotas": 2,
        "gols_pro": 7,
        "gols_contra": 6,
        "saldo": 1,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 0,
        "gols": 0,
        "ass": 1,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "254",
        "nome": "EDUARDO (NEGUIM)",
        "pontos": 9,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 1,
        "derrotas": 2,
        "gols_pro": 5,
        "gols_contra": 4,
        "saldo": 1,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 0,
        "gols": 1,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "199",
        "nome": "ANTONY (LUCAS LIMA)",
        "pontos": 8,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 0,
        "derrotas": 3,
        "gols_pro": 6,
        "gols_contra": 10,
        "saldo": -4,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 0,
        "gols": 1,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "272",
        "nome": "JONATHAN (FARAY)",
        "pontos": 8,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 0,
        "derrotas": 3,
        "gols_pro": 6,
        "gols_contra": 9,
        "saldo": -3,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 0,
        "gols": 1,
        "ass": 1,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "296",
        "nome": "RAFAEL (GABRIEL MIRANDA)",
        "pontos": 8,
        "cotas": 2,
        "jogos": 8,
        "vitorias": 1,
        "empates": 0,
        "derrotas": 7,
        "gols_pro": 7,
        "gols_contra": 18,
        "saldo": -11,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 1,
        "gols": 0,
        "ass": 3,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "207",
        "nome": "GUSTAVO (LUCAS LIMA)",
        "pontos": 6,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 0,
        "empates": 1,
        "derrotas": 3,
        "gols_pro": 7,
        "gols_contra": 12,
        "saldo": -5,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 1,
        "quarto": 0,
        "gols": 2,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "297",
        "nome": "STIVE (VICTOR FERRAZ)",
        "pontos": 4,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 1,
        "derrotas": 2,
        "gols_pro": 7,
        "gols_contra": 7,
        "saldo": 0,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 0,
        "ass": 0,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "291",
        "nome": "DOUGLAS (IGOR)",
        "pontos": 4,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 1,
        "derrotas": 2,
        "gols_pro": 6,
        "gols_contra": 6,
        "saldo": 0,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 0,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "289",
        "nome": "ALEIXO (FARAY)",
        "pontos": 4,
        "cotas": 2,
        "jogos": 8,
        "vitorias": 1,
        "empates": 1,
        "derrotas": 6,
        "gols_pro": 12,
        "gols_contra": 21,
        "saldo": -9,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 2,
        "gols": 2,
        "ass": 2,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "256",
        "nome": "FILIPIM",
        "pontos": 3,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 0,
        "derrotas": 3,
        "gols_pro": 6,
        "gols_contra": 10,
        "saldo": -4,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 0,
        "ass": 3,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "196",
        "nome": "EBER (LUCAS LIMA)",
        "pontos": 3,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 0,
        "derrotas": 3,
        "gols_pro": 5,
        "gols_contra": 8,
        "saldo": -3,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "257",
        "nome": "TACINHO",
        "pontos": 3,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 1,
        "empates": 0,
        "derrotas": 3,
        "gols_pro": 6,
        "gols_contra": 10,
        "saldo": -4,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 4,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "269",
        "nome": "EDILENO",
        "pontos": 3,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 0,
        "empates": 3,
        "derrotas": 1,
        "gols_pro": 4,
        "gols_contra": 5,
        "saldo": -1,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 0,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "288",
        "nome": "ANDERSON (GABRIEL MIRANDA)",
        "pontos": 2,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 0,
        "empates": 2,
        "derrotas": 2,
        "gols_pro": 4,
        "gols_contra": 8,
        "saldo": -4,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "270",
        "nome": "VICTOR EMMANUEL",
        "pontos": 2,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 0,
        "empates": 2,
        "derrotas": 2,
        "gols_pro": 1,
        "gols_contra": 6,
        "saldo": -5,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 0,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "281",
        "nome": "LUCAS PAIVA (FARAY)",
        "pontos": 1,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 0,
        "empates": 1,
        "derrotas": 3,
        "gols_pro": 0,
        "gols_contra": 9,
        "saldo": -9,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "237",
        "nome": "RENATO FERREIRA",
        "pontos": 1,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 0,
        "empates": 1,
        "derrotas": 3,
        "gols_pro": 3,
        "gols_contra": 6,
        "saldo": -3,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "260",
        "nome": "RENATO MOREIRA",
        "pontos": 0,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 0,
        "empates": 0,
        "derrotas": 4,
        "gols_pro": 5,
        "gols_contra": 11,
        "saldo": -6,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 0,
        "ass": 1,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "261",
        "nome": "MATHEUS MOREIRA",
        "pontos": 0,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 0,
        "empates": 0,
        "derrotas": 4,
        "gols_pro": 5,
        "gols_contra": 11,
        "saldo": -6,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 1,
        "ass": 0,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "41",
        "nome": "ALEXANDRE",
        "pontos": 0,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 0,
        "empates": 0,
        "derrotas": 4,
        "gols_pro": 0,
        "gols_contra": 10,
        "saldo": -10,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    },
    {
        "id": "204",
        "nome": "ENDREW (MOISES)",
        "pontos": 0,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 0,
        "empates": 0,
        "derrotas": 4,
        "gols_pro": 3,
        "gols_contra": 11,
        "saldo": -8,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 0,
        "ass": 0,
        "amarelo": 1,
        "vermelho": 0
    },
    {
        "id": "187",
        "nome": "PEDRO FERREIRA",
        "pontos": 0,
        "cotas": 1,
        "jogos": 4,
        "vitorias": 0,
        "empates": 0,
        "derrotas": 4,
        "gols_pro": 4,
        "gols_contra": 13,
        "saldo": -9,
        "primeiro": 0,
        "segundo": 0,
        "terceiro": 0,
        "quarto": 1,
        "gols": 0,
        "ass": 0,
        "amarelo": 0,
        "vermelho": 0
    }
]

const estados =
[
    {
        "id": 11,
        "sigla": "RO",
        "nome": "Rondônia",
        "regiao": {
            "id": 1,
            "sigla": "N",
            "nome": "Norte"
        }
    },
    {
        "id": 12,
        "sigla": "AC",
        "nome": "Acre",
        "regiao": {
            "id": 1,
            "sigla": "N",
            "nome": "Norte"
        }
    },
    {
        "id": 13,
        "sigla": "AM",
        "nome": "Amazonas",
        "regiao": {
            "id": 1,
            "sigla": "N",
            "nome": "Norte"
        }
    },
    {
        "id": 14,
        "sigla": "RR",
        "nome": "Roraima",
        "regiao": {
            "id": 1,
            "sigla": "N",
            "nome": "Norte"
        }
    },
    {
        "id": 15,
        "sigla": "PA",
        "nome": "Pará",
        "regiao": {
            "id": 1,
            "sigla": "N",
            "nome": "Norte"
        }
    },
    {
        "id": 16,
        "sigla": "AP",
        "nome": "Amapá",
        "regiao": {
            "id": 1,
            "sigla": "N",
            "nome": "Norte"
        }
    },
    {
        "id": 17,
        "sigla": "TO",
        "nome": "Tocantins",
        "regiao": {
            "id": 1,
            "sigla": "N",
            "nome": "Norte"
        }
    },
    {
        "id": 21,
        "sigla": "MA",
        "nome": "Maranhão",
        "regiao": {
            "id": 2,
            "sigla": "NE",
            "nome": "Nordeste"
        }
    },
    {
        "id": 22,
        "sigla": "PI",
        "nome": "Piauí",
        "regiao": {
            "id": 2,
            "sigla": "NE",
            "nome": "Nordeste"
        }
    },
    {
        "id": 23,
        "sigla": "CE",
        "nome": "Ceará",
        "regiao": {
            "id": 2,
            "sigla": "NE",
            "nome": "Nordeste"
        }
    },
    {
        "id": 24,
        "sigla": "RN",
        "nome": "Rio Grande do Norte",
        "regiao": {
            "id": 2,
            "sigla": "NE",
            "nome": "Nordeste"
        }
    },
    {
        "id": 25,
        "sigla": "PB",
        "nome": "Paraíba",
        "regiao": {
            "id": 2,
            "sigla": "NE",
            "nome": "Nordeste"
        }
    },
    {
        "id": 26,
        "sigla": "PE",
        "nome": "Pernambuco",
        "regiao": {
            "id": 2,
            "sigla": "NE",
            "nome": "Nordeste"
        }
    },
    {
        "id": 27,
        "sigla": "AL",
        "nome": "Alagoas",
        "regiao": {
            "id": 2,
            "sigla": "NE",
            "nome": "Nordeste"
        }
    },
    {
        "id": 28,
        "sigla": "SE",
        "nome": "Sergipe",
        "regiao": {
            "id": 2,
            "sigla": "NE",
            "nome": "Nordeste"
        }
    },
    {
        "id": 29,
        "sigla": "BA",
        "nome": "Bahia",
        "regiao": {
            "id": 2,
            "sigla": "NE",
            "nome": "Nordeste"
        }
    },
    {
        "id": 31,
        "sigla": "MG",
        "nome": "Minas Gerais",
        "regiao": {
            "id": 3,
            "sigla": "SE",
            "nome": "Sudeste"
        }
    },
    {
        "id": 32,
        "sigla": "ES",
        "nome": "Espírito Santo",
        "regiao": {
            "id": 3,
            "sigla": "SE",
            "nome": "Sudeste"
        }
    },
    {
        "id": 33,
        "sigla": "RJ",
        "nome": "Rio de Janeiro",
        "regiao": {
            "id": 3,
            "sigla": "SE",
            "nome": "Sudeste"
        }
    },
    {
        "id": 35,
        "sigla": "SP",
        "nome": "São Paulo",
        "regiao": {
            "id": 3,
            "sigla": "SE",
            "nome": "Sudeste"
        }
    },
    {
        "id": 41,
        "sigla": "PR",
        "nome": "Paraná",
        "regiao": {
            "id": 4,
            "sigla": "S",
            "nome": "Sul"
        }
    },
    {
        "id": 42,
        "sigla": "SC",
        "nome": "Santa Catarina",
        "regiao": {
            "id": 4,
            "sigla": "S",
            "nome": "Sul"
        }
    },
    {
        "id": 43,
        "sigla": "RS",
        "nome": "Rio Grande do Sul",
        "regiao": {
            "id": 4,
            "sigla": "S",
            "nome": "Sul"
        }
    },
    {
        "id": 50,
        "sigla": "MS",
        "nome": "Mato Grosso do Sul",
        "regiao": {
            "id": 5,
            "sigla": "CO",
            "nome": "Centro-Oeste"
        }
    },
    {
        "id": 51,
        "sigla": "MT",
        "nome": "Mato Grosso",
        "regiao": {
            "id": 5,
            "sigla": "CO",
            "nome": "Centro-Oeste"
        }
    },
    {
        "id": 52,
        "sigla": "GO",
        "nome": "Goiás",
        "regiao": {
            "id": 5,
            "sigla": "CO",
            "nome": "Centro-Oeste"
        }
    },
    {
        "id": 53,
        "sigla": "DF",
        "nome": "Distrito Federal",
        "regiao": {
            "id": 5,
            "sigla": "CO",
            "nome": "Centro-Oeste"
        }
    }
]


// 1. Filtrar alunos do curso de Engenharia e imprimir seus nomes

for (let i = 0; i < alunos.length; i++) {

    console.log(`Aluno: ${alunos[i].nome} - Curso: ${alunos[i].curso}`)

}

// 2. Encontrar o aluno mais velho e imprimir seu nome e idade

let maiorIdade = 0
let nome = ''

for (let i = 0; i < alunos.length; i++) {

    if (maiorIdade < alunos[i].idade) {

        maiorIdade = alunos[i].idade
        nome = alunos[i].nome

    }

}

// console.log(`O aluno com a maior idade foi o(a) ${nome} com idade de ${maiorIdade} anos.`)

// 3. Calcular a média de idade dos alunos

let soma = 0

for (let i = 0; i < alunos.length; i++) {

    soma = soma + alunos[i].idade

}

console.log(`A média das ${alunos.length} idades foi de ${Math.floor(soma/alunos.length)} `)